SecRuleEngine On
SecAuditEngine RelevantOnly
SecAuditLogRelevantStatus "^(?:5|4(?!04))"
SecAuditLogType Serial
SecAuditLog /dev/stdout
SecAuditLogFormat JSON
SecAuditLogParts ABFHJZ

# Paranoia level base. Raise gradually after observing false positives.
SecAction "id:900000,phase:1,pass,nolog,setvar:tx.paranoia_level=1"

