DEFAULT_RULE_CATEGORIES = [
    {
        "key": "protocol",
        "name": "Protocol enforcement",
        "description": "Validaciones de protocolo HTTP, metodos, headers y formato de request.",
        "crs_tag": "OWASP_CRS/PROTOCOL-ENFORCEMENT",
    },
    {
        "key": "method-enforcement",
        "name": "Method enforcement",
        "description": "Control de metodos HTTP permitidos y restricciones de metodo.",
        "crs_tag": "OWASP_CRS/METHOD-ENFORCEMENT",
    },
    {
        "key": "protocol-attack",
        "name": "Protocol attack",
        "description": "Abusos del protocolo HTTP como request smuggling, splitting o evasion.",
        "crs_tag": "OWASP_CRS/PROTOCOL-ATTACK",
    },
    {
        "key": "multipart",
        "name": "Multipart attack",
        "description": "Validaciones especificas de multipart/form-data y cargas de archivo.",
        "crs_tag": "OWASP_CRS/MULTIPART-ATTACK",
    },
    {
        "key": "dos",
        "name": "DoS protection",
        "description": "Reglas CRS de proteccion contra denegacion de servicio a nivel aplicacion.",
        "crs_tag": "OWASP_CRS/DOS-PROTECTION",
    },
    {
        "key": "ip-reputation",
        "name": "IP reputation",
        "description": "Reglas de reputacion de IP incluidas en CRS.",
        "crs_tag": "OWASP_CRS/IP-REPUTATION",
    },
    {
        "key": "scanner",
        "name": "Scanner detection",
        "description": "Deteccion de scanners, crawlers agresivos y herramientas automatizadas.",
        "crs_tag": "OWASP_CRS/AUTOMATION",
    },
    {
        "key": "sqli",
        "name": "SQL injection",
        "description": "Reglas OWASP CRS para patrones de inyeccion SQL.",
        "crs_tag": "attack-sqli",
    },
    {
        "key": "xss",
        "name": "Cross-site scripting",
        "description": "Reglas OWASP CRS para payloads y vectores XSS.",
        "crs_tag": "attack-xss",
    },
    {
        "key": "lfi",
        "name": "Local file inclusion",
        "description": "Intentos de incluir o leer archivos locales sensibles.",
        "crs_tag": "attack-lfi",
    },
    {
        "key": "rfi",
        "name": "Remote file inclusion",
        "description": "Intentos de inclusion remota de recursos maliciosos.",
        "crs_tag": "attack-rfi",
    },
    {
        "key": "rce",
        "name": "Remote command execution",
        "description": "Patrones asociados a ejecucion remota de comandos.",
        "crs_tag": "attack-rce",
    },
    {
        "key": "php",
        "name": "PHP attack",
        "description": "Patrones especificos de ataques contra aplicaciones PHP.",
        "crs_tag": "attack-php",
    },
    {
        "key": "java",
        "name": "Java attack",
        "description": "Patrones especificos de ataques contra aplicaciones Java.",
        "crs_tag": "attack-java",
    },
    {
        "key": "nodejs",
        "name": "Node.js attack",
        "description": "Patrones especificos de ataques contra aplicaciones Node.js.",
        "crs_tag": "attack-nodejs",
    },
    {
        "key": "session-fixation",
        "name": "Session fixation",
        "description": "Intentos de fijacion o abuso de identificadores de sesion.",
        "crs_tag": "attack-session-fixation",
    },
    {
        "key": "data-leakage",
        "name": "Filtración de datos",
        "description": "Inspección de respuestas HTTP en busca de datos sensibles (errores SQL, stack traces, versiones de servidor). Puede generar falsos positivos en APIs que devuelven logs de seguridad como Grafana/Loki.",
        "crs_tag": "OWASP_CRS/DATA-LEAKAGES",
        "enabled_by_default": False,
    },
    {
        "key": "correlation",
        "name": "Correlación de ataques",
        "description": "Reglas de correlación que consolidan eventos de ataque al final de la transacción. Desactivar solo si se observan falsos positivos en el cierre de requests.",
        "crs_tag": "OWASP_CRS/CORRELATION",
        "enabled_by_default": False,
    },
]
