import base64
import hashlib
import hmac as _hmac_mod
import json as _json
import random
import time
from pathlib import Path
from urllib.parse import urlparse

from flask import current_app

from app.extensions import db
from app.models import (
    AppConfig,
    BotProtectionConfig,
    CustomModSecurityRule,
    RuleCategory,
    SecurityHeader,
    Site,
    SiteRuleSetting,
    TrafficPolicy,
)
from app.proxy.catalog import DEFAULT_RULE_CATEGORIES
from app.proxy.nginx_extra import ensure_site_nginx_extra_config
from app.proxy.security_headers import ensure_site_security_headers


def parse_upstream_host_port(upstream_url: str) -> tuple[str | None, int | None]:
    """Return (hostname, port) from an upstream URL. Applies scheme defaults (http=80, https=443)."""
    parsed = urlparse(upstream_url)
    host = parsed.hostname
    port = parsed.port
    if port is None:
        port = 443 if parsed.scheme == "https" else 80
    return host, port


def is_host_docker_internal(upstream_url: str) -> bool:
    """Return True when the upstream resolves to host.docker.internal (a host-exposed port)."""
    host, _ = parse_upstream_host_port(upstream_url)
    return host == "host.docker.internal"


def ensure_default_rule_categories() -> None:
    existing = {category.key for category in RuleCategory.query.all()}
    for item in DEFAULT_RULE_CATEGORIES:
        if item["key"] not in existing:
            db.session.add(RuleCategory(**item))
    db.session.commit()


def sync_site_rule_settings(site: Site) -> None:
    categories = RuleCategory.query.order_by(RuleCategory.name).all()
    existing = {setting.category_id for setting in site.rule_settings}
    for category in categories:
        if category.id not in existing:
            db.session.add(
                SiteRuleSetting(
                    site=site,
                    category=category,
                    enabled=category.enabled_by_default,
                )
            )
    db.session.commit()


def ensure_site_bot_protection(site: Site) -> BotProtectionConfig:
    if site.bot_protection is None:
        cfg = BotProtectionConfig(site=site)
        db.session.add(cfg)
        db.session.commit()
    return site.bot_protection


def ensure_site_traffic_policy(site: Site) -> TrafficPolicy:
    if site.traffic_policy is None:
        policy = TrafficPolicy(site=site)
        db.session.add(policy)
        db.session.commit()
    return site.traffic_policy


def render_nginx_configs() -> list[Path]:
    output_dir = Path(current_app.config["PROXY_CONFIG_DIR"])
    output_dir.mkdir(parents=True, exist_ok=True)

    for stale_file in output_dir.glob("site-*.conf"):
        stale_file.unlink()

    challenge_dir = output_dir / "challenge"
    challenge_dir.mkdir(exist_ok=True)
    challenge_path = challenge_dir / "challenge.html"
    challenge_path.write_text(_build_challenge_html(), encoding="utf-8")

    error_pages_dir = output_dir / "error-pages"
    error_pages_dir.mkdir(exist_ok=True)
    (error_pages_dir / "wn-blocked-403.html").write_text(
        _build_waf_block_html(), encoding="utf-8"
    )

    rendered_files = []

    zones_path = output_dir / "00-zones.conf"
    zones_path.write_text(_render_traffic_zones(), encoding="utf-8")
    rendered_files.append(zones_path)

    geoip_path = output_dir / "00-geoip.conf"
    geoip_db = current_app.config.get("GEOIP_DB_PATH", "")
    geoip_path.write_text(_render_geoip_conf(geoip_db), encoding="utf-8")
    rendered_files.append(geoip_path)

    default_path = output_dir / "01-default-server.conf"
    default_path.write_text(_render_default_server_config(), encoding="utf-8")
    rendered_files.append(default_path)

    for stale_map in output_dir.glob("10-blocklist-site-*.map"):
        stale_map.unlink()

    for site in Site.query.order_by(Site.domain).all():
        ensure_site_traffic_policy(site)
        ensure_site_security_headers(site)
        ensure_site_nginx_extra_config(site)
        ensure_site_bot_protection(site)
        rendered = _render_site_config(site)
        path = output_dir / f"site-{site.id}-{_safe_name(site.domain)}.conf"
        path.write_text(rendered, encoding="utf-8")
        rendered_files.append(path)

    from app.proxy.geoip_blocklist import write_blocklist_conf
    rendered_files.extend(write_blocklist_conf())

    return rendered_files


def _render_default_server_config() -> str:
    """Bloque catch-all que captura tráfico directo a la IP en puerto 80.
    ModSecurity activo: registra violaciones antes de cerrar la conexión con 444."""
    return """\
# Generated by WardNode — catch-all para rechazar tráfico directo a la IP.
server {
    listen 80 default_server;
    server_name _;

    access_log /var/log/nginx/access.json json_combined;
    error_log  /var/log/nginx/error.log warn;

    modsecurity on;
    modsecurity_rules '
        SecRuleEngine On
    ';

    return 444;
}
"""


def _render_geoip_conf(db_path: str) -> str:
    db_filename = Path(db_path).name if db_path else "GeoLite2-Country.mmdb"
    container_db_path = f"/etc/nginx/geoip/{db_filename}"
    db_exists = Path(db_path).exists() if db_path else False

    sites = Site.query.order_by(Site.id).all()

    if db_exists:
        maps = "\n".join(
            f"map $geoip2_country_code $geo_blocked_site_{s.id} {{\n"
            f"    default 0;\n"
            f"    include /etc/nginx/generated/10-blocklist-site-{s.id}.map;\n"
            f"}}"
            for s in sites
        )
        return f"""# Generated by WardNode — GeoIP configuration. Do not edit manually.
geoip2 {container_db_path} {{
    auto_reload 24h;
    $geoip2_country_code default=XX country iso_code;
}}

{maps}
"""
    # DB not available — define per-site variables as constant 0 so server blocks compile.
    maps_fallback = "\n".join(
        f"geo $geo_blocked_site_{s.id} {{\n    default 0;\n}}"
        for s in sites
    )
    return f"""# Generated by WardNode — GeoIP unavailable (DB not found). Blocking disabled.
{maps_fallback}
"""


def _render_site_config(site: Site) -> str:
    parsed_upstream = urlparse(site.upstream_url)
    scheme = parsed_upstream.scheme or "http"
    host = parsed_upstream.netloc or parsed_upstream.path

    disabled_tags = [
        setting.category.crs_tag
        for setting in site.rule_settings
        if not setting.enabled
    ]
    disabled_rules = "\n".join(
        f'        SecRuleRemoveByTag "{tag}"' for tag in disabled_tags
    )
    custom_rules = _render_custom_rules(site)

    waf_state = "On" if site.waf_enabled else "DetectionOnly"
    ssl_block = _ssl_block(site)
    tls_active = bool(ssl_block.strip())
    traffic_directives = _render_location_traffic_directives(site)
    security_header_directives = _render_security_headers(site)
    server_extra = _render_server_extra(site)
    location_extra = _render_location_extra(site)
    obs_location = _render_obs_location(site)
    console_admin_location = _render_console_admin_location(site)

    bot_cfg = ensure_site_bot_protection(site)
    bot_challenge_location = _render_bot_challenge_location() if bot_cfg.enabled else ""
    bot_check = _render_bot_check() if bot_cfg.enabled else ""
    waf_block_location = _render_waf_block_location()

    https_server = f"""server {{
    {ssl_block if tls_active else "listen 80;"}
    server_name {site.domain};

    if ($geo_blocked_site_{site.id}) {{
        return 444;
    }}

    modsecurity on;
    modsecurity_rules '
        SecRuleEngine {waf_state}
{disabled_rules}
{custom_rules}
    ';

    access_log /var/log/nginx/access.json json_combined;
    error_log /var/log/nginx/error.log warn;

{security_header_directives}
{server_extra}
{bot_challenge_location}
{waf_block_location}
{obs_location}
{console_admin_location}
    location /.well-known/acme-challenge/ {{
        root /var/www/certbot;
    }}

    location / {{
{bot_check}
{traffic_directives}
{location_extra}
        proxy_pass {scheme}://{host};
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_http_version 1.1;
    }}
}}
"""

    if site.force_https and tls_active:
        http_redirect = f"""server {{
    listen 80;
    server_name {site.domain};

    location /.well-known/acme-challenge/ {{
        root /var/www/certbot;
    }}

    location / {{
        return 301 https://$host$request_uri;
    }}
}}
"""
        return http_redirect + "\n" + https_server

    # Combined HTTP + HTTPS block (no redirect)
    listen_http = "listen 80;"
    return f"""server {{
    {listen_http}
    {ssl_block}
    server_name {site.domain};

    if ($geo_blocked_site_{site.id}) {{
        return 444;
    }}

    modsecurity on;
    modsecurity_rules '
        SecRuleEngine {waf_state}
{disabled_rules}
{custom_rules}
    ';

    access_log /var/log/nginx/access.json json_combined;
    error_log /var/log/nginx/error.log warn;

{security_header_directives}
{server_extra}
{bot_challenge_location}
{waf_block_location}
{obs_location}
{console_admin_location}
    location /.well-known/acme-challenge/ {{
        root /var/www/certbot;
    }}

    location / {{
{bot_check}
{traffic_directives}
{location_extra}
        proxy_pass {scheme}://{host};
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_http_version 1.1;
    }}
}}
"""


def _render_traffic_zones() -> str:
    lines = [
        "# Generated by WardNode. Do not edit manually.",
    ]
    for site in Site.query.order_by(Site.id).all():
        policy = ensure_site_traffic_policy(site)
        key = _traffic_key(policy)
        if policy.rate_limit_enabled:
            lines.append(
                f"limit_req_zone {key} zone=req_site_{site.id}:10m "
                f"rate={policy.requests_per_second}r/s;"
            )
        if policy.conn_limit_enabled:
            lines.append(f"limit_conn_zone {key} zone=conn_site_{site.id}:10m;")
    return "\n".join(lines) + "\n"


def _render_obs_location(site: Site) -> str:
    if not site.is_console:
        return ""

    return """    location /obs/ {
        modsecurity off;
        auth_request /_wardnode_obs_auth;
        proxy_pass http://127.0.0.1:3000$request_uri;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_set_header X-WEBAUTH-USER admin;
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "upgrade";
        proxy_hide_header X-Frame-Options;
        proxy_hide_header Content-Security-Policy;
        add_header X-Frame-Options "SAMEORIGIN" always;
        add_header Content-Security-Policy "frame-ancestors 'self'" always;
        proxy_read_timeout 300s;
    }

    location = /_wardnode_obs_auth {
        internal;
        modsecurity off;
        proxy_pass http://127.0.0.1:5000/modules/obs/auth;
        proxy_pass_request_body off;
        proxy_set_header Content-Length "";
        proxy_set_header X-Original-URI $request_uri;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_set_header Host $host;
    }

"""


def _render_console_admin_location(site: Site) -> str:
    """Location block con modsecurity off para las rutas de admin de la consola.

    Las rutas /proxy/, /modules/, /audit/ y /auth/ procesan valores de
    configuración de seguridad (directivas CSP, reglas ModSec, headers HTTP)
    que contienen caracteres legítimos que OWASP CRS detecta como XSS/inyección.
    Deshabilitar WAF solo en estas rutas (protegidas por auth + RBAC + CSRF)
    previene falsos positivos sin exponer el sitio a tráfico público.
    """
    if not site.is_console:
        return ""
    parsed = urlparse(site.upstream_url)
    scheme = parsed.scheme or "http"
    host = parsed.netloc or parsed.path
    return f"""    location ~* ^/(proxy|modules|audit|auth)/ {{
        modsecurity off;
        proxy_pass {scheme}://{host};
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_http_version 1.1;
    }}

"""


def _render_location_traffic_directives(site: Site) -> str:
    policy = ensure_site_traffic_policy(site)
    lines = []
    if policy.rate_limit_enabled:
        nodelay = " nodelay" if policy.nodelay else ""
        lines.append(
            f"        limit_req zone=req_site_{site.id} burst={policy.burst}{nodelay};"
        )
    if policy.conn_limit_enabled:
        lines.append(f"        limit_conn conn_site_{site.id} {policy.max_connections};")
    return "\n".join(lines)


_HSTS_VALUES: dict[str, str] = {
    "1y":             "max-age=31536000",
    "1y-sub":         "max-age=31536000; includeSubDomains",
    "1y-sub-preload": "max-age=31536000; includeSubDomains; preload",
}


def _render_security_headers(site: Site) -> str:
    ensure_site_security_headers(site)
    lines = []

    # HSTS gestionado por site.hsts_mode (tiene prioridad sobre la tabla de headers).
    # Se emite primero para que aparezca al inicio del bloque de headers en el config.
    if site.hsts_mode in _HSTS_VALUES:
        lines.append(
            f'    add_header Strict-Transport-Security'
            f' "{_HSTS_VALUES[site.hsts_mode]}" always;'
        )

    for header in site.security_headers:
        if not header.enabled:
            continue
        # Si el select HSTS está activo, omitir el registro de la tabla para
        # evitar duplicados (el select ya emitió el header arriba).
        if header.name.lower() == "strict-transport-security" and site.hsts_mode != "off":
            continue
        always = " always" if header.always else ""
        lines.append(
            f'    add_header {header.name} "{_escape_nginx_header_value(header.value)}"{always};'
        )
    return "\n".join(lines)


def _render_custom_rules(site: Site) -> str:
    lines = []
    for rule in site.custom_rules:
        if not rule.enabled:
            continue
        lines.extend(f"        {line}" for line in rule.rule_text.splitlines() if line.strip())
    return "\n".join(lines)


def _render_server_extra(site: Site) -> str:
    config = ensure_site_nginx_extra_config(site)
    if not config.enabled or not config.server_snippet.strip():
        return ""
    return _indent_nginx_snippet(config.server_snippet, 4)


def _render_location_extra(site: Site) -> str:
    config = ensure_site_nginx_extra_config(site)
    if not config.enabled or not config.location_snippet.strip():
        return ""
    return _indent_nginx_snippet(config.location_snippet, 8)


def _indent_nginx_snippet(snippet: str, spaces: int) -> str:
    prefix = " " * spaces
    return "\n".join(prefix + line if line.strip() else "" for line in snippet.splitlines())


def _escape_nginx_header_value(value: str) -> str:
    return value.replace("\\", "\\\\").replace('"', '\\"')


def _traffic_key(policy: TrafficPolicy) -> str:
    if policy.key_strategy == "forwarded_for":
        return "$http_x_forwarded_for"
    return "$binary_remote_addr"


def _ssl_block(site: Site) -> str:
    cert = site.custom_certificate_path
    key = site.custom_certificate_key_path
    if site.letsencrypt_enabled:
        if site.letsencrypt_status != "active":
            return ""
        cert = f"/etc/letsencrypt/live/{site.domain}/fullchain.pem"
        key = f"/etc/letsencrypt/live/{site.domain}/privkey.pem"

    if not cert or not key:
        return ""

    return f"""listen 443 ssl;
    http2 on;
    ssl_certificate {cert};
    ssl_certificate_key {key};"""


def provision_letsencrypt(site: Site, email: str) -> tuple[bool, str]:
    """Full LE provisioning: nginx HTTP-only → certbot → nginx with TLS (step 1 only)."""
    from app.proxy.geoip_blocklist import reload_nginx

    render_nginx_configs()
    ok_reload, err_reload = reload_nginx()
    if not ok_reload:
        return False, f"Nginx no recargó para servir el challenge ACME: {err_reload}"

    try:
        import docker as docker_sdk
        client = docker_sdk.from_env()
        container_name = current_app.config.get("NGINX_CONTAINER_NAME", "wardnode-proxy")
        proxy = client.containers.get(container_name)
        mounts = {
            m["Destination"]: m["Name"]
            for m in proxy.attrs["Mounts"]
            if m["Type"] == "volume"
        }
        le_vol = mounts.get("/etc/letsencrypt")
        cb_vol = mounts.get("/var/www/certbot")
        if not le_vol or not cb_vol:
            return False, "Volúmenes letsencrypt/certbot no encontrados en el proxy"

        client.containers.run(
            "certbot/certbot:latest",
            command=(
                f"certonly --webroot -w /var/www/certbot -d {site.domain} "
                f"--email {email} --agree-tos --non-interactive"
            ),
            volumes={
                le_vol: {"bind": "/etc/letsencrypt", "mode": "rw"},
                cb_vol: {"bind": "/var/www/certbot", "mode": "rw"},
            },
            remove=True,
            detach=False,
        )
        return True, ""
    except Exception as exc:
        stderr = getattr(exc, "stderr", b"") or b""
        msg = stderr.decode("utf-8", errors="replace").strip() if stderr else str(exc)
        return False, msg


def _safe_name(value: str) -> str:
    return "".join(char if char.isalnum() else "-" for char in value).strip("-")


def _make_challenge(secret: str) -> dict:
    """Generate a server-side HMAC-signed challenge (question, shuffled choices, token).

    The token encodes the correct answer, signed with the app SECRET_KEY.
    The correct answer is NOT exposed in the HTML/JS — only the choices are.
    """
    op = random.choice(["+", "-", "*"])
    if op == "+":
        a, b = random.randint(5, 20), random.randint(3, 15)
        answer = a + b
        question = f"{a} + {b}"
    elif op == "-":
        a = random.randint(12, 30)
        b = random.randint(3, a - 3)
        answer = a - b
        question = f"{a} \u2212 {b}"   # − (unicode minus)
    else:
        a, b = random.randint(2, 9), random.randint(2, 9)
        answer = a * b
        question = f"{a} \xd7 {b}"    # × (unicode times)

    # Sign the correct answer — answer is never sent to the client in plain text
    payload = base64.urlsafe_b64encode(_json.dumps({"a": answer}).encode()).decode()
    sig = _hmac_mod.new(secret.encode(), payload.encode(), hashlib.sha256).hexdigest()[:32]
    token = f"{payload}.{sig}"

    choices: set[int] = {answer}
    while len(choices) < 3:
        delta = random.choice([-3, -2, -1, 1, 2, 3])
        c = answer + delta
        if c > 0:
            choices.add(c)
    shuffled = list(choices)
    random.shuffle(shuffled)

    return {"question": question, "choices": shuffled, "token": token}


def _render_bot_challenge_location() -> str:
    console_url = current_app.config.get("WN_CONSOLE_URL", "http://console:5000").rstrip("/")
    return f"""
    location = /_wn_challenge/verify {{
        proxy_pass {console_url}/proxy/bot-verify;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_read_timeout 10s;
    }}

    location /_wn_challenge/ {{
        alias /etc/nginx/generated/challenge/;
        index challenge.html;
        try_files $uri /challenge.html =404;
        add_header Cache-Control "no-cache, no-store, must-revalidate" always;
    }}
"""


def _render_bot_check() -> str:
    return '        if ($cookie_wn_bot != "ward_cleared_v1") {\n            return 302 /_wn_challenge/?ret=$request_uri;\n        }'


def _render_waf_block_location() -> str:
    return """
    error_page 403 /wn-blocked-403.html;

    location = /wn-blocked-403.html {
        root /etc/nginx/generated/error-pages;
        internal;
        add_header Cache-Control "no-cache, no-store, must-revalidate" always;
    }
"""


def _build_challenge_html() -> str:
    """Build the bot challenge page with a server-side generated question.

    The correct answer is signed server-side (HMAC-SHA256) and never exposed
    in plain text in the HTML/JS. The user's choice is submitted via form POST
    to /_wn_challenge/verify (proxied to Flask), which sets the HttpOnly cookie.
    """
    secret = current_app.config.get("SECRET_KEY", "change-me")
    challenge = _make_challenge(secret)

    # json.dumps produces valid JS literals; replace < > to prevent </script> injection
    choices_js = _json.dumps(challenge["choices"]).replace("<", r"\u003c").replace(">", r"\u003e")
    question_js = _json.dumps(challenge["question"]).replace("<", r"\u003c").replace(">", r"\u003e")
    token_js = _json.dumps(challenge["token"]).replace("<", r"\u003c").replace(">", r"\u003e")

    return f"""<!DOCTYPE html>
<html lang="es">
<head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<title>Verificación · WardNode</title>
<link rel="preconnect" href="https://fonts.googleapis.com">
<link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
<link href="https://fonts.googleapis.com/css2?family=Plus+Jakarta+Sans:wght@400;500;600;700&display=swap" rel="stylesheet">
<style>
  *, *::before, *::after {{ box-sizing: border-box; margin: 0; padding: 0; }}

  body {{
    min-height: 100vh;
    display: flex;
    flex-direction: column;
    align-items: center;
    justify-content: center;
    background-color: #0b1120;
    background-image:
      linear-gradient(rgba(59,130,246,.04) 1px, transparent 1px),
      linear-gradient(90deg, rgba(59,130,246,.04) 1px, transparent 1px);
    background-size: 32px 32px;
    font-family: 'Plus Jakarta Sans', system-ui, sans-serif;
    color: #e2e8f0;
    padding: 24px;
  }}

  .card {{
    background: rgba(255,255,255,.04);
    border: 1px solid rgba(255,255,255,.08);
    border-radius: 16px;
    padding: 48px 40px 40px;
    max-width: 420px;
    width: 100%;
    text-align: center;
    backdrop-filter: blur(8px);
  }}

  .logo-wrap {{
    position: relative;
    display: inline-flex;
    align-items: center;
    justify-content: center;
    margin-bottom: 32px;
  }}

  .logo-glow {{
    position: absolute;
    width: 160px;
    height: 160px;
    border-radius: 50%;
    background: radial-gradient(circle, rgba(59,130,246,.25) 0%, transparent 70%);
    animation: glow-pulse 3s ease-in-out infinite;
  }}

  @keyframes glow-pulse {{
    0%, 100% {{ opacity: .6; transform: scale(1); }}
    50%       {{ opacity: 1;  transform: scale(1.12); }}
  }}

  .logo-svg {{
    position: relative;
    z-index: 1;
    color: #fff;
    animation: logo-float 4s ease-in-out infinite;
    filter: drop-shadow(0 0 18px rgba(59,130,246,.5));
  }}

  @keyframes logo-float {{
    0%, 100% {{ transform: translateY(0); }}
    50%       {{ transform: translateY(-5px); }}
  }}

  .app-name {{
    font-size: 11px;
    font-weight: 600;
    letter-spacing: .12em;
    text-transform: uppercase;
    color: #3b82f6;
    margin-bottom: 8px;
  }}

  h1 {{
    font-size: 20px;
    font-weight: 700;
    color: #f1f5f9;
    margin-bottom: 6px;
    letter-spacing: -.01em;
  }}

  .subtitle {{
    font-size: 13px;
    color: #64748b;
    margin-bottom: 36px;
    line-height: 1.5;
  }}

  .challenge-label {{
    font-size: 11px;
    font-weight: 600;
    letter-spacing: .06em;
    text-transform: uppercase;
    color: #475569;
    margin-bottom: 12px;
  }}

  .equation {{
    font-size: 32px;
    font-weight: 700;
    color: #e2e8f0;
    margin-bottom: 24px;
    letter-spacing: -.02em;
  }}

  .options {{
    display: grid;
    grid-template-columns: repeat(3, 1fr);
    gap: 10px;
    margin-bottom: 28px;
  }}

  .opt-btn {{
    background: rgba(255,255,255,.06);
    border: 1px solid rgba(255,255,255,.1);
    border-radius: 10px;
    color: #e2e8f0;
    font-family: inherit;
    font-size: 20px;
    font-weight: 700;
    padding: 16px 8px;
    cursor: pointer;
    transition: background .15s, border-color .15s, transform .1s;
  }}

  .opt-btn:hover:not(:disabled) {{
    background: rgba(59,130,246,.15);
    border-color: rgba(59,130,246,.4);
    transform: translateY(-2px);
  }}

  .opt-btn:disabled {{ opacity: .5; cursor: not-allowed; }}

  .opt-btn.pending {{
    background: rgba(59,130,246,.15);
    border-color: rgba(59,130,246,.4);
    animation: correct-pop .4s ease;
  }}

  .opt-btn.wrong {{
    background: rgba(239,68,68,.12);
    border-color: rgba(239,68,68,.4);
    color: #fca5a5;
    animation: shake .3s ease;
  }}

  @keyframes correct-pop {{
    0%   {{ transform: scale(1); }}
    40%  {{ transform: scale(1.08); }}
    100% {{ transform: scale(1); }}
  }}

  @keyframes shake {{
    0%,100% {{ transform: translateX(0); }}
    25%      {{ transform: translateX(-6px); }}
    75%      {{ transform: translateX(6px); }}
  }}

  .status-msg {{
    font-size: 13px;
    color: #64748b;
    min-height: 20px;
    margin-bottom: 4px;
  }}

  .footer {{
    margin-top: 40px;
    font-size: 11px;
    color: #1e3a5f;
    letter-spacing: .04em;
  }}

  .footer strong {{ color: #243c5e; }}
</style>
</head>
<body>

<form id="challenge-form" method="POST" action="/_wn_challenge/verify" style="display:none">
  <input type="hidden" id="token-field"  name="token"  value="">
  <input type="hidden" id="ret-field"    name="ret"    value="">
  <input type="hidden" id="choice-field" name="choice" value="">
</form>

<div class="card">
  <div class="logo-wrap">
    <div class="logo-glow"></div>
    <svg class="logo-svg" width="72" height="86" viewBox="0 0 22 26" fill="none" xmlns="http://www.w3.org/2000/svg">
      <path d="M11 1.5 L20.5 5.2 V14 C20.5 19.8 16.2 24.2 11 25.5 C5.8 24.2 1.5 19.8 1.5 14 V5.2 Z"
            stroke="currentColor" stroke-width="1.6" stroke-linejoin="round" stroke-linecap="round"/>
      <circle cx="11" cy="16.5" r="1.8" fill="currentColor"/>
      <line x1="10.1" y1="15.3" x2="5.8" y2="10.2" stroke="currentColor" stroke-width="1.6" stroke-linecap="round"/>
      <line x1="11.9" y1="15.3" x2="16.2" y2="10.2" stroke="currentColor" stroke-width="1.6" stroke-linecap="round"/>
      <line x1="11" y1="18.3" x2="11" y2="22.2" stroke="currentColor" stroke-width="1.6" stroke-linecap="round"/>
    </svg>
  </div>

  <p class="app-name">WardNode</p>
  <h1>Verificación de seguridad</h1>
  <p class="subtitle">Resuelve el siguiente desafío para<br>demostrar que no eres un bot.</p>

  <p class="challenge-label">¿Cuánto es?</p>
  <div class="equation" id="equation">…</div>

  <div class="options" id="options"></div>
  <p class="status-msg" id="status"></p>
</div>

<p class="footer">Protegido por <strong>WardNode</strong> · Bot Protection</p>

<script>
(function () {{
  const CHOICES  = {choices_js};
  const QUESTION = {question_js};
  const TOKEN    = {token_js};

  const params  = new URLSearchParams(window.location.search);
  const rawRet  = params.get("ret") || "/";
  /* Validate returnTo: must be a relative path, not a protocol-relative or absolute URL */
  const safeRet = (rawRet.startsWith("/") && !rawRet.startsWith("//")) ? rawRet : "/";
  const hasError = params.get("error") === "1";

  document.getElementById("equation").textContent  = QUESTION + "  =  ?";
  document.getElementById("ret-field").value        = safeRet;
  document.getElementById("token-field").value      = TOKEN;

  const statusEl  = document.getElementById("status");
  const optionsEl = document.getElementById("options");

  if (hasError) {{
    statusEl.textContent = "Incorrecto · intenta de nuevo.";
    statusEl.style.color = "#ef4444";
  }}

  CHOICES.forEach(function(val) {{
    const btn = document.createElement("button");
    btn.type      = "button";
    btn.className = "opt-btn";
    btn.textContent = val;
    btn.addEventListener("click", function() {{
      document.querySelectorAll(".opt-btn").forEach(function(b) {{ b.disabled = true; }});
      btn.classList.add("pending");
      statusEl.textContent = "Verificando…";
      statusEl.style.color = "#94a3b8";
      document.getElementById("choice-field").value = val;
      document.getElementById("challenge-form").submit();
    }});
    optionsEl.appendChild(btn);
  }});
}})();
</script>
</body>
</html>"""


def _build_waf_block_html() -> str:
    return """<!DOCTYPE html>
<html lang="es">
<head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<title>Acceso Bloqueado · WardNode</title>
<link rel="preconnect" href="https://fonts.googleapis.com">
<link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
<link href="https://fonts.googleapis.com/css2?family=Plus+Jakarta+Sans:wght@400;500;600;700&display=swap" rel="stylesheet">
<style>
  *, *::before, *::after { box-sizing: border-box; margin: 0; padding: 0; }

  body {
    min-height: 100vh;
    display: flex;
    flex-direction: column;
    align-items: center;
    justify-content: center;
    background-color: #0b1120;
    background-image:
      linear-gradient(rgba(59,130,246,.04) 1px, transparent 1px),
      linear-gradient(90deg, rgba(59,130,246,.04) 1px, transparent 1px);
    background-size: 32px 32px;
    font-family: 'Plus Jakarta Sans', system-ui, sans-serif;
    color: #e2e8f0;
    padding: 24px;
  }

  .card {
    background: rgba(255,255,255,.04);
    border: 1px solid rgba(255,255,255,.08);
    border-radius: 16px;
    padding: 48px 40px 40px;
    max-width: 420px;
    width: 100%;
    text-align: center;
    backdrop-filter: blur(8px);
  }

  .logo-wrap {
    position: relative;
    display: inline-flex;
    align-items: center;
    justify-content: center;
    margin-bottom: 32px;
  }

  .logo-glow {
    position: absolute;
    width: 160px;
    height: 160px;
    border-radius: 50%;
    background: radial-gradient(circle, rgba(239,68,68,.28) 0%, transparent 70%);
    animation: glow-pulse 3s ease-in-out infinite;
  }

  @keyframes glow-pulse {
    0%, 100% { opacity: .6; transform: scale(1); }
    50%       { opacity: 1;  transform: scale(1.12); }
  }

  .logo-svg {
    position: relative;
    z-index: 1;
    color: #ef4444;
    animation: logo-float 4s ease-in-out infinite;
    filter: drop-shadow(0 0 18px rgba(239,68,68,.55));
  }

  @keyframes logo-float {
    0%, 100% { transform: translateY(0); }
    50%       { transform: translateY(-5px); }
  }

  .app-name {
    font-size: 11px;
    font-weight: 600;
    letter-spacing: .12em;
    text-transform: uppercase;
    color: #ef4444;
    margin-bottom: 8px;
  }

  h1 {
    font-size: 20px;
    font-weight: 700;
    color: #f1f5f9;
    margin-bottom: 6px;
    letter-spacing: -.01em;
  }

  .subtitle {
    font-size: 13px;
    color: #64748b;
    margin-bottom: 24px;
    line-height: 1.5;
  }

  .detail {
    font-size: 12px;
    color: #475569;
    line-height: 1.7;
    padding: 14px 16px;
    background: rgba(239,68,68,.05);
    border: 1px solid rgba(239,68,68,.12);
    border-radius: 8px;
  }

  .footer {
    margin-top: 40px;
    font-size: 11px;
    color: #1e3a5f;
    letter-spacing: .04em;
  }

  .footer strong { color: #243c5e; }
</style>
</head>
<body>

<div class="card">
  <div class="logo-wrap">
    <div class="logo-glow"></div>
    <svg class="logo-svg" width="72" height="86" viewBox="0 0 22 26" fill="none" xmlns="http://www.w3.org/2000/svg">
      <path d="M11 1.5 L20.5 5.2 V14 C20.5 19.8 16.2 24.2 11 25.5 C5.8 24.2 1.5 19.8 1.5 14 V5.2 Z"
            stroke="currentColor" stroke-width="1.6" stroke-linejoin="round" stroke-linecap="round"/>
      <circle cx="11" cy="16.5" r="1.8" fill="currentColor"/>
      <line x1="10.1" y1="15.3" x2="5.8" y2="10.2" stroke="currentColor" stroke-width="1.6" stroke-linecap="round"/>
      <line x1="11.9" y1="15.3" x2="16.2" y2="10.2" stroke="currentColor" stroke-width="1.6" stroke-linecap="round"/>
      <line x1="11" y1="18.3" x2="11" y2="22.2" stroke="currentColor" stroke-width="1.6" stroke-linecap="round"/>
    </svg>
  </div>

  <p class="app-name">WardNode</p>
  <h1>Acceso Bloqueado</h1>
  <p class="subtitle">WardNode WAF ha bloqueado esta solicitud<br>por motivos de seguridad.</p>

  <div class="detail">
    Si crees que esto es un error,<br>contacta al administrador del sitio.
  </div>
</div>

<p class="footer">Protegido por <strong>WardNode</strong> · WAF</p>

</body>
</html>"""
